services:
  db:
    image: mysql:8
    container_name: lpkniweb-DB
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lpkni_web_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: lpkni_web_db

volumes:  
  mysql_data: